name: Label Pull Request

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  label:
    permissions: write-all
    uses: jco-digital/jcore-module-actions/.github/workflows/label.yml@v1.0.0
